# Generated by Django 2.0.5 on 2018-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.IntegerField(primary_key=True,default=0)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('revenue', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('conversions', models.IntegerField()),
            ],
        ),
    ]
